#!/usr/bin/env python3
"""Deterministically render the structured code-hygiene catalog as Markdown."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = REPO_ROOT / "data" / "code-hygiene" / "catalog.json"
SOURCES_PATH = REPO_ROOT / "data" / "code-hygiene" / "sources.json"
ROUTING_PATH = REPO_ROOT / "data" / "code-hygiene" / "routing-fixtures.json"
CONTENT_ROOT = REPO_ROOT / "content" / "recipes" / "general" / "code-hygiene"
GENERATED_MARKER = "<!-- Generated by scripts/sync_code_hygiene_recipes.py; edit data/code-hygiene/catalog.json. -->"


def load_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return payload


def yaml_scalar(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def yaml_list(values: list[str]) -> str:
    return json.dumps(values, ensure_ascii=False)


def recipe_id(record: dict[str, Any]) -> str:
    return f"code-hygiene.{record['family']}.{record['slug']}"


def recipe_path(record: dict[str, Any]) -> Path:
    return CONTENT_ROOT / record["family"] / f"{record['slug']}.md"


def recipe_url(record: dict[str, Any]) -> str:
    return f"/recipes/general/code-hygiene/{record['family']}/{record['slug']}/"


def references_for(
    record: dict[str, Any], families: dict[str, Any], sources: dict[str, Any]
) -> list[dict[str, str]]:
    source_by_id = {source["id"]: source for source in sources["sources"]}
    ids = ["nist-ssdf", *families[record["family"]].get("references", []), *record.get("references", [])]
    unique_ids = list(dict.fromkeys(ids))
    return [source_by_id[source_id] for source_id in unique_ids]


def related_records(record: dict[str, Any], records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    siblings = [item for item in records if item["family"] == record["family"] and item["slug"] != record["slug"]]
    if len(siblings) >= 2:
        return siblings[:2]
    others = [item for item in records if item["slug"] != record["slug"] and item not in siblings]
    return (siblings + others)[:2]


def render_recipe(
    record: dict[str, Any], catalog: dict[str, Any], sources: dict[str, Any], family_weight: int, item_weight: int
) -> str:
    family = catalog["families"][record["family"]]
    ecosystem = record.get("ecosystem") or family["ecosystem"]
    tags = list(dict.fromkeys(["code-hygiene", record["family"], *record["tags"]]))
    refs = references_for(record, catalog["families"], sources)
    ref_ids = [ref["id"] for ref in refs]
    description = f"Bounded audit or remediation to {record['goal']}."
    related = related_records(record, catalog["records"])
    frontmatter = [
        "---",
        f"title: {yaml_scalar(record['title'])}",
        f"linkTitle: {yaml_scalar(record['title'])}",
        f"description: {yaml_scalar(description)}",
        'tool: "general"',
        'author: "security-recipes.ai contributors"',
        'team: "Security Engineering"',
        'maturity: "development"',
        'model: "gpt-5-codex"',
        f"recipe_id: {yaml_scalar(recipe_id(record))}",
        'recipe_kind: "code-hygiene"',
        f"scope: {yaml_scalar(record['family'])}",
        f"ecosystem: {yaml_scalar(ecosystem)}",
        'facets: ["code-hygiene", "audit", "remediation"]',
        f"tags: {yaml_list(tags)}",
        f"weight: {family_weight * 100 + item_weight}",
        f"date: {catalog['generated_date']}",
        f"reference_ids: {yaml_list(ref_ids)}",
        f"references_reviewed: {sources['reviewed_on']}",
        "---",
        "",
        GENERATED_MARKER,
        "",
    ]

    prompt_lines = [
        f"You are running the Security Recipes code-hygiene workflow `{recipe_id(record)}`.",
        "",
        "Start read-only. Do not edit files until the operator explicitly authorizes a fix.",
        "Use repository configuration and installed tool versions as authoritative; do not impose a new style or toolchain.",
        "",
        "### Scope",
        "",
        f"Your bounded objective is to {record['goal']}.",
        "Inspect only operator-scoped, first-party source and configuration. Exclude generated, vendored, minified, fixture snapshot, lock history, and migration history unless explicitly included.",
        "",
        "### Detection",
        "",
        *[f"- {signal}" for signal in record["detect"]],
        "- Record file and symbol evidence for every candidate. Mark uncertain or dynamically reachable behavior instead of guessing.",
        "",
        "### Fix, only when authorized",
        "",
        f"- {record['fix']}",
        "- Keep the diff limited to the proven issue and its focused tests. Preserve public behavior, API compatibility, and repository conventions.",
        "- Do not add or broaden suppressions, weaken diagnostics, mass-format unrelated files, upgrade dependencies, or mutate external state.",
        "",
        "### Verification",
        "",
        f"- {record['verify']}",
        "- Compare diagnostic counts and relevant behavior before and after. Report every command, result, and check that could not run.",
        "",
        "### Stop conditions",
        "",
        f"- {record['stop']}",
        "- Stop and hand off to a focused security recipe if evidence indicates a vulnerability, secret exposure, authorization failure, injection path, or named CVE.",
        "- Stop rather than widening scope when the safe result requires architecture, product, compliance, operational, or data-owner decisions.",
    ]

    body = [
        f"A tool-agnostic recipe to {record['goal']}. It supports a read-only audit and, when explicitly authorized, a narrow remediation.",
        "",
        "## When to use it",
        "",
        f"Use this recipe when the operator's specific objective is to {record['goal']}. Prefer a narrower CVE, scanner-finding, security-audit, or compliance-evidence recipe when that is the operator's actual job.",
        "",
        "## Inputs",
        "",
        "- Repository root and the files, package, service, or module in scope.",
        "- Requested mode: `audit` or explicitly authorized `fix`.",
        "- Supported runtime, compiler, framework, operating-system, and deployment versions inferred from repository files.",
        "- Existing formatter, compiler, analyzer, test, build, and package-manager commands.",
        "- Public API, compatibility, performance, generated-code, vendor, and migration constraints.",
        "",
        "## The prompt",
        "",
        "~~~markdown",
        *prompt_lines,
        "~~~",
        "",
        "## Output contract",
        "",
        "- Scope and repository evidence reviewed.",
        "- A candidate table with file or symbol, evidence, confidence, and disposition.",
        "- In audit mode: no edits, plus the smallest safe next action for each confirmed item.",
        "- In fix mode: one bounded patch, focused regression coverage, and no unrelated cleanup.",
        "- Commands run, results, remaining uncertainty, and any stop-condition handoff.",
        "",
        "## Verification",
        "",
        f"- {record['verify']}",
        "- Confirm that diagnostic configuration, suppressions, public interfaces, generated files, vendored files, and dependencies did not change outside the authorized scope.",
        "- Review the final diff for behavior changes and run the repository's focused checks before broader suites.",
        "",
        "## Guardrails",
        "",
        "- Read-only until edits are explicitly authorized.",
        "- Do not deploy, publish, rotate secrets, alter cloud or database state, change CI permissions, or open external tickets.",
        "- Do not hide debt by disabling rules, adding retries or sleeps, weakening tests, broadening ignores, or lowering warning levels.",
        "- Treat generated, vendored, minified, migration-history, and fixture-snapshot files as out of scope unless explicitly named.",
        f"- {record['stop']}",
        "",
        "## Related recipes",
        "",
        *[
            f"- [{item['title']}]({{{{< relref \"{recipe_url(item).rstrip('/')}\" >}}}})"
            for item in related
        ],
        "- [Browse all code-hygiene recipes]({{< relref \"/recipes/general/code-hygiene\" >}})",
        "",
        "## References",
        "",
        *[f"- [{ref['title']}]({ref['url']}) — {ref['owner']}" for ref in refs],
        "",
    ]
    return "\n".join(frontmatter + body)


def render_root_index(catalog: dict[str, Any]) -> str:
    return "\n".join(
        [
            "---",
            'title: "Code Hygiene Recipes"',
            'linkTitle: "Code Hygiene"',
            'description: "Bounded audit and remediation recipes for code correctness, maintainability, lifecycle safety, and diagnostic debt across major ecosystems."',
            "weight: 22",
            "sidebar:",
            "  open: false",
            "---",
            "",
            GENERATED_MARKER,
            "",
            "Use the narrowest ecosystem recipe that matches the repository. Cross-language recipes are intended for polyglot or language-independent work. Each recipe starts read-only and requires explicit authorization before edits.",
            "",
            "{{< callout type=\"warning\" >}}",
            "Code hygiene is not a substitute for vulnerability triage. Named CVEs, scanner findings, authorization, injection, secrets, and compliance-evidence work should use their focused recipes.",
            "{{< /callout >}}",
            "",
            "## Ecosystem families",
            "",
            "{{< prompt-toc >}}",
            "",
        ]
    )


def render_family_index(
    key: str,
    family: dict[str, Any],
    weight: int,
    records: list[dict[str, Any]],
) -> str:
    family_records = [record for record in records if record["family"] == key]
    return "\n".join(
        [
            "---",
            f"title: {yaml_scalar(family['title'] + ' Code Hygiene')}",
            f"linkTitle: {yaml_scalar(family['title'])}",
            f"description: {yaml_scalar(family['description'])}",
            f"weight: {weight * 10}",
            "sidebar:",
            "  open: false",
            "---",
            "",
            GENERATED_MARKER,
            "",
            family["description"],
            "",
            f"## Choose a focused {family['title']} recipe",
            "",
            f"This collection contains {len(family_records)} bounded {family['title']} workflows. Choose the recipe whose objective matches the repository evidence instead of combining unrelated cleanup into one run.",
            "",
            *[
                f"- **[{record['title']}]({{{{< relref \"{recipe_url(record).rstrip('/')}\" >}}}}):** Use it to {record['goal']}."
                for record in family_records
            ],
            "",
            "## How to use this collection",
            "",
            "Read the repository's configured runtime, compiler, framework, analyzer, and test commands before selecting a workflow. Start in audit mode, record file and symbol evidence, and authorize a fix only after the candidate scope is reviewable. Preserve supported versions, public behavior, and existing tool configuration.",
            "",
            "If the evidence is a named CVE, scanner finding, exposed secret, authorization flaw, or injection path, use the focused vulnerability-remediation playbook instead of a code-hygiene recipe. Stop when the safe result requires an owner decision about architecture, compatibility, production data, or deployment state.",
            "",
            "## Full recipe list",
            "",
            "{{< prompt-toc >}}",
            "",
        ]
    )


def routing_fixture(catalog: dict[str, Any]) -> str:
    cases: list[dict[str, Any]] = []
    families = catalog["families"]
    for record in catalog["records"]:
        ecosystem = record.get("ecosystem") or families[record["family"]]["ecosystem"]
        path = recipe_url(record)
        cases.extend(
            [
                {
                    "id": f"{recipe_id(record)}.title",
                    "query": f"{record['title']} {ecosystem} {' '.join(record['tags'][:3])}",
                    "expected_recipe_id": recipe_id(record),
                    "expected_paths": [path],
                },
                {
                    "id": f"{recipe_id(record)}.evidence",
                    "query": f"{record['goal']} {record['detect'][0]}",
                    "expected_recipe_id": recipe_id(record),
                    "expected_paths": [path],
                },
            ]
        )
    payload = {
        "schema_version": 1,
        "name": "code-hygiene recipe routing fixtures",
        "version": catalog["generated_date"],
        "positive_case_count": len(cases),
        "positive_cases": cases,
        "hard_negative_cases": catalog["hard_negative_cases"],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def expected_outputs(catalog: dict[str, Any], sources: dict[str, Any]) -> dict[Path, str]:
    outputs: dict[Path, str] = {CONTENT_ROOT / "_index.md": render_root_index(catalog), ROUTING_PATH: routing_fixture(catalog)}
    family_order = list(catalog["families"])
    for family_weight, (key, family) in enumerate(catalog["families"].items(), start=1):
        outputs[CONTENT_ROOT / key / "_index.md"] = render_family_index(
            key,
            family,
            family_weight,
            catalog["records"],
        )
    item_counts: dict[str, int] = {}
    for record in catalog["records"]:
        item_counts[record["family"]] = item_counts.get(record["family"], 0) + 1
        outputs[recipe_path(record)] = render_recipe(
            record,
            catalog,
            sources,
            family_order.index(record["family"]) + 1,
            item_counts[record["family"]],
        )
    return outputs


def _is_link_or_junction(path: Path) -> bool:
    is_junction = getattr(path, "is_junction", None)
    return path.is_symlink() or bool(is_junction and is_junction())


def _managed_content_entries() -> list[tuple[Path, str, str]]:
    """Return the generated content tree post-order without following links."""

    if _is_link_or_junction(CONTENT_ROOT):
        raise ValueError(f"generated content root must not be a link or junction: {CONTENT_ROOT}")
    if CONTENT_ROOT.exists() and not CONTENT_ROOT.is_dir():
        raise ValueError(f"generated content root must be a directory: {CONTENT_ROOT}")
    if not CONTENT_ROOT.exists():
        return []
    entries: list[tuple[Path, str, str]] = []

    def visit(directory: Path) -> None:
        with os.scandir(directory) as scanned:
            children = sorted(scanned, key=lambda entry: entry.name)
        for child in children:
            path = Path(child.path)
            relative = path.relative_to(CONTENT_ROOT).as_posix()
            if child.is_symlink() or _is_link_or_junction(path):
                entries.append((path, relative, "link"))
            elif child.is_dir(follow_symlinks=False):
                visit(path)
                entries.append((path, relative, "directory"))
            elif child.is_file(follow_symlinks=False):
                entries.append((path, relative, "file"))
            else:
                entries.append((path, relative, "special"))

    visit(CONTENT_ROOT)
    return entries


def reconcile_content_tree(expected_paths: set[Path], *, check: bool) -> list[str]:
    """Reconcile the fully generated Markdown subtree to its catalog outputs."""

    expected = {path.relative_to(CONTENT_ROOT).as_posix() for path in expected_paths}
    expected_dirs = {
        parent.as_posix()
        for relative in expected
        for parent in Path(relative).parents
        if parent.as_posix() != "."
    }
    stale: list[str] = []
    for path, relative, kind in _managed_content_entries():
        remove = (
            kind in {"link", "special"}
            or (kind == "file" and relative not in expected)
            or (kind == "directory" and relative not in expected_dirs)
        )
        if not remove:
            continue
        stale.append(str((CONTENT_ROOT / relative).relative_to(REPO_ROOT)))
        if check:
            continue
        if kind == "directory":
            path.rmdir()
        elif kind == "link" and bool(getattr(path, "is_junction", lambda: False)()) and not path.is_symlink():
            path.rmdir()
        else:
            path.unlink()
    return stale


def sync(check: bool = False) -> list[str]:
    catalog = load_json(CATALOG_PATH)
    sources = load_json(SOURCES_PATH)
    outputs = expected_outputs(catalog, sources)
    content_paths = {path for path in outputs if path.is_relative_to(CONTENT_ROOT)}
    stale = reconcile_content_tree(content_paths, check=check)
    for path, rendered in outputs.items():
        current = (
            path.read_text(encoding="utf-8")
            if path.is_file() and not _is_link_or_junction(path)
            else None
        )
        if current == rendered:
            continue
        stale.append(str(path.relative_to(REPO_ROOT)))
        if not check:
            if _is_link_or_junction(path):
                if bool(getattr(path, "is_junction", lambda: False)()) and not path.is_symlink():
                    path.rmdir()
                else:
                    path.unlink()
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered, encoding="utf-8", newline="\n")
    return sorted(set(stale))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report generated files that are missing or stale.")
    args = parser.parse_args()
    stale = sync(check=args.check)
    if args.check and stale:
        print("Code-hygiene generated outputs are stale:", file=sys.stderr)
        for path in stale:
            print(f"- {path}", file=sys.stderr)
        return 1
    action = "checked" if args.check else "rendered"
    print(f"Code-hygiene catalog {action}: 72 recipes, 15 family indexes, 144 routing fixtures.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
